name: Frontend CI

on:
  push:
    branches: ["main", "master"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main", "master"]
    paths:
      - "frontend/**"

jobs:
  frontend-build:
    name: Frontend CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/the-eye-org/nexus-frontend

    defaults:
      run:
        working-directory: ./frontend/fr

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/nexus/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint || echo "No lint configured"

      - name: Build project
        run: npm run build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: .
        run: |
          VERSION=0.1-${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION ./frontend/fr
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION

      - name: Notify Jenkins
        run: |
          curl --insecure "${{ secrets.JENKINS_FRONTEND_URL }}"
